# Generated by Django 3.2.16 on 2023-01-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_courier_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
