# Generated by Django 3.2.16 on 2023-01-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifier',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='modifiergroup',
            name='photo',
        ),
        migrations.AddField(
            model_name='modifier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='modifiers',
            field=models.ManyToManyField(related_name='groups', to='restaurant.Modifier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modifier_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='restaurant.ModifierGroup'),
        ),
    ]
