# Generated by Django 3.2.16 on 2023-01-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20230121_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifier',
            name='slug',
        ),
        migrations.AlterField(
            model_name='modifiergroup',
            name='modifiers',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='restaurant.Modifier'),
        ),
        migrations.AlterField(
            model_name='modifiergroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
