# Generated by Django 3.2.16 on 2023-01-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20230126_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='catprods', to='restaurant.Product'),
        ),
    ]
