# Generated by Django 3.2.16 on 2023-01-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20230121_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
